### ISSUE TITLE
CircleCIでビルドエラー

### ISSUE THREAD

**Issue by makotok** [cmknet/knowledge#6]
https://circleci.com/gh/cmknet/knowledge/20

```
[INFO] copy emoji
[ERROR] /home/circleci/repo/node_modules/fs-extra/lib/index.js:5
[ERROR]   ...require('./fs'),
[ERROR]   ^^^
[ERROR] SyntaxError: Unexpected token ...
[ERROR]     at Object.exports.runInThisContext (vm.js:76:16)
[ERROR]     at Module._compile (module.js:542:28)
[ERROR]     at Object.Module._extensions..js (module.js:579:10)
[ERROR]     at Module.load (module.js:487:32)
[ERROR]     at tryModuleLoad (module.js:446:12)
[ERROR]     at Function.Module._load (module.js:438:3)
[ERROR]     at Module.require (module.js:497:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (/home/circleci/repo/copy-emoji.js:3:10)
[ERROR]     at Module._compile (module.js:570:32)
[ERROR] 
[ERROR] npm ERR! Linux 5.3.0-1019-aws
[ERROR] npm ERR! argv "/home/circleci/repo/node/node" "/home/circleci/repo/node/node_modules/npm/bin/npm-cli.js" "run" "emoji"
[ERROR] npm ERR! node v6.9.2
[ERROR] npm ERR! npm  v3.10.9
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! knowledge@1.0.0 emoji: `node copy-emoji.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the knowledge@1.0.0 emoji script 'node copy-emoji.js'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the knowledge package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node copy-emoji.js
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs knowledge
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls knowledge
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/circleci/repo/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:31 min
[INFO] Finished at: 2020-06-05T23:48:01+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (copy emoji) on project knowledge: Failed to run task: 'npm run emoji' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by makotok** [comment]
fs-extra@9.0.1だと、knowledgeが利用するnode.jsのバージョンだと動作しないことが分かった。
バージョンを8.1.0で固定するように修正してみる。

**Comment by makotok** [comment]
修正後、ビルドエラーが解消されたことを確認
